apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-serp
  labels:
    app: google-serp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google-serp
  template:
    metadata:
      labels:
        app: google-serp
    spec:
      containers:
        - name: google-serp
          image: olivier86/google-serp:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: TWO_CAPTCHA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-serp-secrets
                  key: two-captcha-api-key
            - name: PROXY_SERVER
              valueFrom:
                secretKeyRef:
                  name: google-serp-secrets
                  key: proxy-server
            - name: PROXY_USERNAME
              valueFrom:
                secretKeyRef:
                  name: google-serp-secrets
                  key: proxy-username
            - name: PROXY_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: google-serp-secrets
                  key: proxy-password
          resources:
            requests:
              memory: "0.75Gi"
              cpu: "750m" # 0.75 CPU
            limits:
              memory: "1Gi"
              cpu: "1000m" # 1 CPU
          readinessProbe:
            httpGet:
              path: /api/search?q=test&pages_nb=1&country=fr
              port: 3001
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 30
