apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-serp
  labels:
    app: google-serp
spec:
  replicas: 3 # Start with 3 instances
  selector:
    matchLabels:
      app: google-serp
  template:
    metadata:
      labels:
        app: google-serp
    spec:
      containers:
        - name: google-serp
          image: olivier86/google-serp:latest
          ports:
            - containerPort: 3001
          env:
            - name: PORT
              value: "3001"
            - name: TWO_CAPTCHA_API_KEY
              valueFrom:
                secretKeyRef:
                  name: google-serp-secrets
                  key: two-captcha-api-key
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m" # 0.25 CPU
            limits:
              memory: "1Gi"
              cpu: "500m" # 0.5 CPU
          readinessProbe:
            httpGet:
              path: /api/search?q=test&pages_nb=1
              port: 3001
            initialDelaySeconds: 90
            periodSeconds: 60
            timeoutSeconds: 30
